os:
  - osx
language: swift
sudo: required
osx_image: xcode11.2
script:
  - set -o pipefail
  - xcodebuild -project GeomKit.xcodeproj -scheme "GeomKit"  -sdk iphonesimulator  -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.2' test
notifications:
  email:
    on_success: never
    on_failure: change
